name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    name: Build, Test and Check Coverage
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: Set executable permissions
        run: chmod +x ./gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build and Test with Coverage
        run: |
          ./gradlew test jacocoTestReport

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Checking Greeting Stream coverage
        run: |
          COVERAGE=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@covered)" greeting-stream/build/reports/jacoco/test/jacocoTestReport.xml)
          MISSED=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@missed)" greeting-stream/build/reports/jacoco/test/jacocoTestReport.xml)
          TOTAL=$((COVERAGE + MISSED))
          PERCENTAGE=$((100 * COVERAGE / TOTAL))
          echo "Coverage is $PERCENTAGE%"
          if [ "$PERCENTAGE" -lt 80 ]; then
            echo "Coverage is below 80% ($PERCENTAGE%)"
            exit 1
          fi
