name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    name: Build, Test and Check Coverage
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build and Test with Coverage
        run: |
          ./gradlew test jacocoTestReport

      - name: Verify Coverage
        run: |
          COVERAGE=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@covered)" build/reports/jacoco/test/jacocoTestReport.xml)
          MISSED=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@missed)" build/reports/jacoco/test/jacocoTestReport.xml)
          TOTAL=$((COVERAGE + MISSED))
          PERCENTAGE=$((100 * COVERAGE / TOTAL))
          echo "Coverage is $PERCENTAGE%"
          if [ "$PERCENTAGE" -lt 80 ]; then
            echo "Coverage is below 80% ($PERCENTAGE%)"
            exit 1
          fi
        shell: bash
